services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=epicevents
    ports:
      - "5432:5432"
    expose:
      - 5432
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=clmtmarcel@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=epicevents
    ports:
      - "5050:80"
    restart: always
